#!/usr/bin/env python3
"""
scaffold_agent.py — Generate a new BMAD agent definition.

Usage:
    python scaffold_agent.py <agent-name> --role "Description of the agent's role"
    python scaffold_agent.py tech-lead --role "Senior Technical Lead" --icon "🏗️"
    python scaffold_agent.py tech-lead --role "Senior Technical Lead" --compile

Creates an .agent.yaml file from the BMAD agent schema with populated
metadata and persona stubs. Optionally compiles to .md format.
"""

import argparse
import re
import sys
from datetime import date
from pathlib import Path

# ---------------------------------------------------------------------------
# ANSI colours
# ---------------------------------------------------------------------------
GREEN = "\033[92m"
YELLOW = "\033[93m"
CYAN = "\033[96m"
RED = "\033[91m"
DIM = "\033[2m"
BOLD = "\033[1m"
RESET = "\033[0m"


def slugify(name: str) -> str:
    """Convert a name to kebab-case identifier."""
    s = name.lower().strip()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-")


def title_case(slug: str) -> str:
    """Convert kebab-case to Title Case."""
    return " ".join(w.capitalize() for w in slug.split("-"))


# ---------------------------------------------------------------------------
# Agent YAML template
# ---------------------------------------------------------------------------

def generate_agent_yaml(
    agent_id: str,
    display_name: str,
    icon: str,
    role: str,
    module: str = "bmm",
) -> str:
    """Generate agent YAML content."""
    return f"""# BMAD Agent Definition — {display_name}
# Generated: {date.today().isoformat()}
# Schema: references/schemas.md > Agent Definition Schema

metadata:
  id: "{agent_id}"
  name: "{display_name}"
  icon: "{icon}"
  module: "{module}"

persona:
  role: "{role}"
  identity: |
    TODO: Describe this agent's background, personality, and area of expertise.
    Include what makes this agent unique and how they approach problems.
    Be specific about their domain knowledge and professional experience.
  communication_style: |
    TODO: Describe how this agent communicates. Examples:
    - Analytical and data-driven, presents findings with confidence levels
    - Collaborative and encouraging, uses questions to guide thinking
    - Direct and concise, focuses on actionable next steps
  principles:
    - "TODO: Core belief or guiding principle #1"
    - "TODO: Core belief or guiding principle #2"
    - "TODO: Core belief or guiding principle #3"

menu:
  - trigger: "XX"
    description: "TODO: Primary workflow name"
    workflow: "workflows/TODO/"
  - trigger: "YY"
    description: "TODO: Secondary workflow name"
    workflow: "workflows/TODO/"

prompts:
  system: |
    You are {display_name}, a {role}.
    TODO: Add system prompt instructions that prime the AI to behave as this agent.
    Include specific domain knowledge, constraints, and behavioral guidelines.
"""


def generate_agent_md(
    agent_id: str,
    display_name: str,
    icon: str,
    role: str,
) -> str:
    """Generate compiled agent markdown."""
    return f"""# {icon} {display_name}

> **Role**: {role}
> **ID**: `{agent_id}`

## Persona

TODO: Describe this agent's background, personality, and area of expertise.

## Communication Style

TODO: How this agent communicates and interacts.

## Principles

1. TODO: Core principle #1
2. TODO: Core principle #2
3. TODO: Core principle #3

## Menu

| Trigger | Workflow | Description |
|---------|----------|-------------|
| `XX` | TODO | Primary workflow |
| `YY` | TODO | Secondary workflow |

## System Prompt

You are {display_name}, a {role}.

TODO: Add full system prompt.

---
*Generated by BMAD scaffold_agent.py on {date.today().isoformat()}*
"""


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate a new BMAD agent definition.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python scaffold_agent.py tech-lead --role "Senior Technical Lead"
  python scaffold_agent.py devops-eng --role "DevOps Engineer" --icon "🔧"
  python scaffold_agent.py tech-lead --role "Senior Technical Lead" --compile
        """,
    )
    parser.add_argument("agent_name", help="Agent name (will be slugified to kebab-case)")
    parser.add_argument("--role", required=True, help="Agent role description")
    parser.add_argument("--icon", default="🤖", help="Single emoji icon (default: 🤖)")
    parser.add_argument("--module", default="bmm", help="Module identifier (default: bmm)")
    parser.add_argument(
        "--output-dir", "-o",
        help="Output directory (default: current directory)",
    )
    parser.add_argument(
        "--compile",
        action="store_true",
        help="Also generate a compiled .md version",
    )

    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview what would be created without writing files",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Show generated file contents in output",
    )

    args = parser.parse_args()

    agent_id = slugify(args.agent_name)
    if not agent_id:
        print(
            f"{RED}[err]{RESET} Invalid agent name: '{args.agent_name}'.\n"
            f"  Fix: use alphanumeric characters and hyphens (e.g., 'tech-lead').",
            file=sys.stderr,
        )
        sys.exit(2)

    display_name = title_case(agent_id)
    icon = args.icon
    role = args.role
    module = args.module

    out_dir = Path(args.output_dir) if args.output_dir else Path.cwd()
    if not out_dir.is_dir():
        print(
            f"{RED}[err]{RESET} Output directory does not exist: {out_dir}\n"
            f"  Fix: create the directory first or use --output-dir with an existing path.",
            file=sys.stderr,
        )
        sys.exit(2)

    yaml_path = out_dir / f"{agent_id}.agent.yaml"
    yaml_content = generate_agent_yaml(agent_id, display_name, icon, role, module)

    if args.dry_run:
        print(f"\n{BOLD}Dry Run — Agent Scaffold Preview{RESET}")
        print(f"  Would create: {yaml_path}")
        if args.compile:
            print(f"  Would create: {out_dir / f'{agent_id}.md'}")
        if args.verbose:
            print(f"\n{DIM}--- YAML content preview ---{RESET}")
            for line in yaml_content.splitlines()[:15]:
                print(f"  {DIM}{line}{RESET}")
            print(f"  {DIM}... ({len(yaml_content.splitlines())} total lines){RESET}")
        print(f"\n{YELLOW}Dry run complete. No files were created.{RESET}\n")
        sys.exit(0)

    # Check for existing file
    if yaml_path.exists():
        print(
            f"{RED}[err]{RESET} File already exists: {yaml_path}\n"
            f"  Fix: choose a different agent name or delete the existing file.",
            file=sys.stderr,
        )
        sys.exit(2)

    # Write YAML
    yaml_path.write_text(yaml_content, encoding="utf-8")
    print(f"{GREEN}[ok]{RESET} Created {yaml_path}")

    # Optionally write MD
    if args.compile:
        md_path = out_dir / f"{agent_id}.md"
        md_content = generate_agent_md(agent_id, display_name, icon, role)
        md_path.write_text(md_content, encoding="utf-8")
        print(f"{GREEN}[ok]{RESET} Created {md_path}")

    print()
    print(f"{BOLD}Next steps:{RESET}")
    print(f"  1. Edit {CYAN}{yaml_path.name}{RESET} — fill in persona, principles, and menu")
    print(f"  2. Define workflows referenced in the menu section")
    print(f"  3. Add the agent to your project's .bmad/agents/ directory")
    print()


if __name__ == "__main__":
    main()
